# Reference: https://www.gitpod.io/docs/references/gitpod-yml
# Docs: https://www.gitpod.io/docs/config-gitpod-file/

tasks:
  - init: npm install -g @sanity/cli

  - openMode: split-right
    command: echo hello
# Ports to expose on workspace startup
ports:
  - port: 3333
    onOpen: open-preview 